---
title: "HLAthena_netmhcpan_physical_properties"
author: "Austin"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyr)
library(ggplot2)
library(reshape2)
library(data.table)
library(dplyr)
setwd("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds")
rm(list=ls())
big_allele_list <- c("HLA-A02:02","HLA-A02:06","HLA-A68:01","HLA-A02:03","HLA-A02:01","H-2-Kb","HLA-A11:01","HLA-A30:02","HLA-A31:01","HLA-B15:01","HLA-B35:01","HLA-A30:01","HLA-B07:02","HLA-A03:01","HLA-A29:02","HLA-A68:02","HLA-B08:01","HLA-B58:01","HLA-A23:01","HLA-A24:02","H-2-Db","HLA-A33:01","HLA-B40:01","HLA-B27:05","HLA-B44:02","HLA-B57:01","HLA-A01:01","HLA-B51:01","HLA-A26:01","HLA-A69:01","HLA-B18:01")
bighlathena_list <- gsub("HLA-", "", big_allele_list)
bighlathena_list <- gsub(":", "", bighlathena_list)
rm(big_allele_list)
```

```{r test_diff_pipeline_cmv}
cmv_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/cmv_hlathena_out.txt")
colnames(cmv_new) <- c("Peptide", "Allele", "Score")
cmv_new$Peptide <- gsub("'", '', cmv_new$Peptide, perl=TRUE)
cmv_new$Allele <- gsub("'", '', cmv_new$Allele, perl=TRUE)
cmv_new$Score <- gsub("'", '', cmv_new$Score, perl=TRUE)
cmv_new_filt <- cmv_new[cmv_new$Allele %in% bighlathena_list,]
cmv_new_filt$Score <- as.numeric(cmv_new_filt$Score)
cmv_new_filt_0.5 <- cmv_new_filt[cmv_new_filt$Score > 0.5,]

rm(cmv_new)
#cmv_old <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/cmv_hlathena-predictions.txt", sep='\t')
#cmv_old_filt <- cmv_old %>% select(1,seq(4,60,2))
#cmv_old_filt <- cmv_old_filt %>% gather(Allele, Score, -pep)
#cmv_old_filt$Allele <- gsub("MSi_", "", cmv_old_filt$Allele, perl=TRUE)
#colnames(cmv_old_filt) <- c("Peptide", "Allele", "Score")
#cmv_old_filt <- cmv_old_filt[cmv_old_filt$Allele %in% bighlathena_list,]

cmv_new_filt_0.5 <- cmv_new_filt[cmv_new_filt$Score > 0.5,]
#cmv_old_filt_0.5 <- cmv_old_filt[cmv_old_filt$Score > 0.5,]
#rm(cmv_old_filt)
#rm(cmv_old)
#rm(cmv_old_filt_0.5)
```


```{r load betaherpes_6a}
betaherpes_6a_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/betaherpes_6a_hlathena_out.txt")
colnames(betaherpes_6a_new) <- c("Peptide", "Allele", "Score")
betaherpes_6a_new$Peptide <- gsub("'", '', betaherpes_6a_new$Peptide, perl=TRUE)
betaherpes_6a_new$Allele <- gsub("'", '', betaherpes_6a_new$Allele, perl=TRUE)
betaherpes_6a_new$Score <- gsub("'", '', betaherpes_6a_new$Score, perl=TRUE)
betaherpes_6a_new_filt <- betaherpes_6a_new[betaherpes_6a_new$Allele %in% bighlathena_list,]
betaherpes_6a_new_filt$Score <- as.numeric(betaherpes_6a_new_filt$Score)
betaherpes_6a_new_filt_0.5 <- betaherpes_6a_new_filt[betaherpes_6a_new_filt$Score > 0.5,]
rm(betaherpes_6a_new)
```

```{r load bk}
bk_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/bk_hlathena_out.txt")
colnames(bk_new) <- c("Peptide", "Allele", "Score")
bk_new$Peptide <- gsub("'", '', bk_new$Peptide, perl=TRUE)
bk_new$Allele <- gsub("'", '', bk_new$Allele, perl=TRUE)
bk_new$Score <- gsub("'", '', bk_new$Score, perl=TRUE)
bk_new_filt <- bk_new[bk_new$Allele %in% bighlathena_list,]
bk_new_filt$Score <- as.numeric(bk_new_filt$Score)
bk_new_filt_0.5 <- bk_new_filt[bk_new_filt$Score > 0.5,]
rm(bk_new)
```

```{r load cmv}
cmv_hlathena <- cmv_new_filt
cmv_hlathena_0.5 <- cmv_new_filt_0.5
rm(cmv_new_filt)
rm(cmv_new_filt_0.5)
```

```{r load covid}
covid_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/covid_hlathena_out.txt")
colnames(covid_new) <- c("Peptide", "Allele", "Score")
covid_new$Peptide <- gsub("'", '', covid_new$Peptide, perl=TRUE)
covid_new$Allele <- gsub("'", '', covid_new$Allele, perl=TRUE)
covid_new$Score <- gsub("'", '', covid_new$Score, perl=TRUE)
covid_new_filt <- covid_new[covid_new$Allele %in% bighlathena_list,]
covid_new_filt$Score <- as.numeric(covid_new_filt$Score)
covid_new_filt_0.5 <- covid_new_filt[covid_new_filt$Score > 0.5,]
rm(covid_new)

```

```{r load ebv}
ebv_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/ebv_hlathena_out.txt")
colnames(ebv_new) <- c("Peptide", "Allele", "Score")
ebv_new$Peptide <- gsub("'", '', ebv_new$Peptide, perl=TRUE)
ebv_new$Allele <- gsub("'", '', ebv_new$Allele, perl=TRUE)
ebv_new$Score <- gsub("'", '', ebv_new$Score, perl=TRUE)
ebv_new_filt <- ebv_new[ebv_new$Allele %in% bighlathena_list,]
ebv_new_filt$Score <- as.numeric(ebv_new_filt$Score)
ebv_new_filt_0.5 <- ebv_new_filt[ebv_new_filt$Score > 0.5,]
rm(ebv_new)

```

```{r load herpes_1_17}
herpes_1_17_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/herpes_1_17_hlathena_out.txt")
colnames(herpes_1_17_new) <- c("Peptide", "Allele", "Score")
herpes_1_17_new$Peptide <- gsub("'", '', herpes_1_17_new$Peptide, perl=TRUE)
herpes_1_17_new$Allele <- gsub("'", '', herpes_1_17_new$Allele, perl=TRUE)
herpes_1_17_new$Score <- gsub("'", '', herpes_1_17_new$Score, perl=TRUE)
herpes_1_17_new_filt <- herpes_1_17_new[herpes_1_17_new$Allele %in% bighlathena_list,]
herpes_1_17_new_filt$Score <- as.numeric(herpes_1_17_new_filt$Score)
herpes_1_17_new_filt_0.5 <- herpes_1_17_new_filt[herpes_1_17_new_filt$Score > 0.5,]
rm(herpes_1_17_new)

```

```{r load herpes_2_hg52}
herpes_2_hg52_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/herpes_2_hg52_hlathena_out.txt")
colnames(herpes_2_hg52_new) <- c("Peptide", "Allele", "Score")
herpes_2_hg52_new$Peptide <- gsub("'", '', herpes_2_hg52_new$Peptide, perl=TRUE)
herpes_2_hg52_new$Allele <- gsub("'", '', herpes_2_hg52_new$Allele, perl=TRUE)
herpes_2_hg52_new$Score <- gsub("'", '', herpes_2_hg52_new$Score, perl=TRUE)
herpes_2_hg52_new_filt <- herpes_2_hg52_new[herpes_2_hg52_new$Allele %in% bighlathena_list,]
herpes_2_hg52_new_filt$Score <- as.numeric(herpes_2_hg52_new_filt$Score)
herpes_2_hg52_new_filt_0.5 <- herpes_2_hg52_new_filt[herpes_2_hg52_new_filt$Score > 0.5,]
rm(herpes_2_hg52_new)

```


```{r load human}
human <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/human_hlathena-predictions.txt", sep="\t")
human_filt <- human %>% select(1,seq(4,60,2))
human_hlathena <- human_filt %>% gather(Allele, Score, -pep)
rm(human)
rm(human_filt)
human_hlathena$Allele <- gsub("MSi_", "", human_hlathena$Allele)
human_new_filt <- human_hlathena[human_hlathena$Allele %in% bighlathena_list,]
human_new_filt$Score <- as.numeric(human_new_filt$Score)
human_new_filt_0.5 <- human_new_filt[human_new_filt$Score > 0.5,]
rm(human_hlathena)
```

```{r load random}
random_new <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/HLAthena_preds/random_hlathena_out.txt")
colnames(random_new) <- c("Peptide", "Allele", "Score")
random_new$Peptide <- gsub("'", '', random_new$Peptide, perl=TRUE)
random_new$Allele <- gsub("'", '', random_new$Allele, perl=TRUE)
random_new$Score <- gsub("'", '', random_new$Score, perl=TRUE)
random_new_filt <- random_new[random_new$Allele %in% bighlathena_list,]
random_new_filt$Score <- as.numeric(random_new_filt$Score)
random_new_filt_0.5 <- random_new_filt[random_new_filt$Score > 0.5,]
rm(random_new)

```


```{r load master_reverse}
#master_reverse_new <- read.csv("master_reverse_out.txt")
#colnames(master_reverse_new) <- c("Peptide", "Allele", "Score")
#master_reverse_new$Peptide <- gsub("'", '', master_reverse_new$Peptide, perl=TRUE)
#master_reverse_new$Allele <- gsub("'", '', master_reverse_new$Allele, perl=TRUE)
#master_reverse_new$Score <- gsub("'", '', master_reverse_new$Score, perl=TRUE)
#master_reverse_new_filt <- master_reverse_new[master_reverse_new$Allele %in% bighlathena_list,]
#master_reverse_new_filt$Score <- as.numeric(master_reverse_new_filt$Score)
#master_reverse_new_filt_0.5 <- master_reverse_new_filt[master_reverse_new_filt$Score > 0.5,]
#rm(master_reverse_new)
```




```{r herpes_6b only}
order <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/herpes_6b_2000netmhcpan_rank_by_cutoffs_hlathena.csv")
order$X <- NULL

listcols <- c(1,seq(2,20,2))
order_only <- order[,listcols]
colnames(order_only) <- c("Var1", seq(0.5,0.95, 0.05))
herpes_6b_order <- order_only
rm(order)
rm(order_only)
herpes_6b_order <- select(herpes_6b_order, c("Var1", "0.5"))
```

```{r select orders}
betaherpes_6a_order <- as.data.frame(table(betaherpes_6a_new_filt_0.5$Allele))
bk_order <- as.data.frame(table(bk_new_filt_0.5$Allele))
cmv_order <- as.data.frame(table(cmv_hlathena_0.5$Allele))
covid_order <- as.data.frame(table(covid_new_filt_0.5$Allele))
ebv_order <- as.data.frame(table(ebv_new_filt_0.5$Allele))
herpes_1_17_order <- as.data.frame(table(herpes_1_17_new_filt_0.5$Allele))
herpes_2_hg52_order <- as.data.frame(table(herpes_2_hg52_new_filt_0.5$Allele))
human_order <- as.data.frame(table(human_new_filt_0.5$Allele))
random_order <- as.data.frame(table(random_new_filt_0.5$Allele))

colnames(herpes_6b_order)[2] <- "herpes_6b"
colnames(betaherpes_6a_order)[2] <- "betaherpes_6a"
colnames(bk_order)[2] <- "bk"
colnames(cmv_order)[2] <- "cmv"
colnames(covid_order)[2] <- "covid"
colnames(ebv_order)[2] <- "ebv"
colnames(herpes_1_17_order)[2] <- "herpes_1_17"
colnames(herpes_2_hg52_order)[2] <- "herpes_2_hg52"
colnames(human_order)[2] <- "human"
colnames(random_order)[2] <- "random"


merged_orders <- merge(herpes_6b_order, betaherpes_6a_order, by="Var1")
merged_orders <- merge(merged_orders, bk_order, by="Var1")
merged_orders <- merge(merged_orders, cmv_order, by="Var1")
merged_orders <- merge(merged_orders, covid_order, by="Var1")
merged_orders <- merge(merged_orders, ebv_order, by="Var1")
merged_orders <- merge(merged_orders, herpes_1_17_order, by="Var1")
merged_orders <- merge(merged_orders, herpes_2_hg52_order, by="Var1")
merged_orders <- merge(merged_orders, human_order, by="Var1")
merged_orders <- merge(merged_orders, random_order, by="Var1")

cormat <- cor(merged_orders[,-1], method="spearman")

write.csv(betaherpes_6a_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/betaherpes_filt.csv")
write.csv(bk_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/bk_filt.csv")
write.csv(cmv_hlathena_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/cmv_filt.csv")
write.csv(covid_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/covid_filt.csv")
write.csv(ebv_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/ebv_filt.csv")
write.csv(herpes_1_17_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/herpes_1_17_filt.csv")
write.csv(herpes_2_hg52_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/herpes_2_hg52_filt.csv")
write.csv(human_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/human_filt.csv")
write.csv(random_new_filt_0.5, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/random_filt.csv")

library(reshape2)
library(ggplot2)
#ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
#  geom_tile()

get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}
upper_tri <- get_upper_tri(cormat)
upper_tri

# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "yellow", 
                       midpoint = 0.5, limit = c(0,1), space = "Lab", 
                       name="Spearman\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 5, hjust = 1))+
  coord_fixed()

```


```{r 8mer orders}
betaherpes_6a_order_8mer <- as.data.frame(table(betaherpes_6a_new_filt_0.5[nchar(betaherpes_6a_new_filt_0.5$Peptide) == 8,]$Allele))
bk_order_8mer <- as.data.frame(table(bk_new_filt_0.5[nchar(bk_new_filt_0.5$Peptide) == 8,]$Allele))
cmv_order_8mer <- as.data.frame(table(cmv_hlathena_0.5[nchar(cmv_hlathena_0.5$Peptide) == 8,]$Allele))
covid_order_8mer <- as.data.frame(table(covid_new_filt_0.5[nchar(covid_new_filt_0.5$Peptide) == 8,]$Allele))
ebv_order_8mer <- as.data.frame(table(ebv_new_filt_0.5[nchar(ebv_new_filt_0.5$Peptide) == 8,]$Allele))
herpes_1_17_order_8mer <- as.data.frame(table(herpes_1_17_new_filt_0.5[nchar(herpes_1_17_new_filt_0.5$Peptide) == 8,]$Allele))
herpes_2_hg52_order_8mer <- as.data.frame(table(herpes_2_hg52_new_filt_0.5[nchar(herpes_2_hg52_new_filt_0.5$Peptide) == 8,]$Allele))
human_order_8mer <- as.data.frame(table(human_new_filt_0.5[nchar(human_new_filt_0.5$pep) == 8,]$Allele))
random_order_8mer <- as.data.frame(table(random_new_filt_0.5[nchar(random_new_filt_0.5$Peptide) == 8,]$Allele))

colnames(betaherpes_6a_order_8mer)[2] <- "betaherpes_6a"
colnames(bk_order_8mer)[2] <- "bk"
colnames(cmv_order_8mer)[2] <- "cmv"
colnames(covid_order_8mer)[2] <- "covid"
colnames(ebv_order_8mer)[2] <- "ebv"
colnames(herpes_1_17_order_8mer)[2] <- "herpes_1_17"
colnames(herpes_2_hg52_order_8mer)[2] <- "herpes_2_hg52"
colnames(human_order_8mer)[2] <- "human"
colnames(random_order_8mer)[2] <- "random"

merged_order_8mers <- merge(betaherpes_6a_order_8mer, bk_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, cmv_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, covid_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, ebv_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, herpes_1_17_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, herpes_2_hg52_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, human_order_8mer, by="Var1")
merged_order_8mers <- merge(merged_order_8mers, random_order_8mer, by="Var1")

cormat <- cor(merged_order_8mers[,-1], method="spearman")

library(reshape2)
library(ggplot2)
#ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
#  geom_tile()

get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}
upper_tri <- get_upper_tri(cormat)
upper_tri

# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "yellow", 
                       midpoint = 0.4, limit = c(-0.2,1), space = "Lab", 
                       name="Spearman\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 5, hjust = 1))+
  coord_fixed()

```



```{r 9mer orders}
betaherpes_6a_order_9mer <- as.data.frame(table(betaherpes_6a_new_filt_0.5[nchar(betaherpes_6a_new_filt_0.5$Peptide) == 9,]$Allele))
bk_order_9mer <- as.data.frame(table(bk_new_filt_0.5[nchar(bk_new_filt_0.5$Peptide) == 9,]$Allele))
cmv_order_9mer <- as.data.frame(table(cmv_hlathena_0.5[nchar(cmv_hlathena_0.5$Peptide) == 9,]$Allele))
covid_order_9mer <- as.data.frame(table(covid_new_filt_0.5[nchar(covid_new_filt_0.5$Peptide) == 9,]$Allele))
ebv_order_9mer <- as.data.frame(table(ebv_new_filt_0.5[nchar(ebv_new_filt_0.5$Peptide) == 9,]$Allele))
herpes_1_17_order_9mer <- as.data.frame(table(herpes_1_17_new_filt_0.5[nchar(herpes_1_17_new_filt_0.5$Peptide) == 9,]$Allele))
herpes_2_hg52_order_9mer <- as.data.frame(table(herpes_2_hg52_new_filt_0.5[nchar(herpes_2_hg52_new_filt_0.5$Peptide) == 9,]$Allele))
human_order_9mer <- as.data.frame(table(human_new_filt_0.5[nchar(human_new_filt_0.5$pep) == 9,]$Allele))
random_order_9mer <- as.data.frame(table(random_new_filt_0.5[nchar(random_new_filt_0.5$Peptide) == 9,]$Allele))

colnames(betaherpes_6a_order_9mer)[2] <- "betaherpes_6a"
colnames(bk_order_9mer)[2] <- "bk"
colnames(cmv_order_9mer)[2] <- "cmv"
colnames(covid_order_9mer)[2] <- "covid"
colnames(ebv_order_9mer)[2] <- "ebv"
colnames(herpes_1_17_order_9mer)[2] <- "herpes_1_17"
colnames(herpes_2_hg52_order_9mer)[2] <- "herpes_2_hg52"
colnames(human_order_9mer)[2] <- "human"
colnames(random_order_9mer)[2] <- "random"

merged_order_9mers <- merge(betaherpes_6a_order_9mer, bk_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, cmv_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, covid_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, ebv_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, herpes_1_17_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, herpes_2_hg52_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, human_order_9mer, by="Var1")
merged_order_9mers <- merge(merged_order_9mers, random_order_9mer, by="Var1")

cormat <- cor(merged_order_9mers[,-1], method="spearman")

library(reshape2)
library(ggplot2)
#ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
#  geom_tile()

get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}
upper_tri <- get_upper_tri(cormat)
upper_tri

# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "yellow", 
                       midpoint = 0.4, limit = c(-0.2,1), space = "Lab", 
                       name="Spearman\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 5, hjust = 1))+
  coord_fixed()

```



```{r 10mer orders}
betaherpes_6a_order_10mer <- as.data.frame(table(betaherpes_6a_new_filt_0.5[nchar(betaherpes_6a_new_filt_0.5$Peptide) == 10,]$Allele))
bk_order_10mer <- as.data.frame(table(bk_new_filt_0.5[nchar(bk_new_filt_0.5$Peptide) == 10,]$Allele))
cmv_order_10mer <- as.data.frame(table(cmv_hlathena_0.5[nchar(cmv_hlathena_0.5$Peptide) == 10,]$Allele))
covid_order_10mer <- as.data.frame(table(covid_new_filt_0.5[nchar(covid_new_filt_0.5$Peptide) == 10,]$Allele))
ebv_order_10mer <- as.data.frame(table(ebv_new_filt_0.5[nchar(ebv_new_filt_0.5$Peptide) == 10,]$Allele))
herpes_1_17_order_10mer <- as.data.frame(table(herpes_1_17_new_filt_0.5[nchar(herpes_1_17_new_filt_0.5$Peptide) == 10,]$Allele))
herpes_2_hg52_order_10mer <- as.data.frame(table(herpes_2_hg52_new_filt_0.5[nchar(herpes_2_hg52_new_filt_0.5$Peptide) == 10,]$Allele))
human_order_10mer <- as.data.frame(table(human_new_filt_0.5[nchar(human_new_filt_0.5$pep) == 10,]$Allele))
random_order_10mer <- as.data.frame(table(random_new_filt_0.5[nchar(random_new_filt_0.5$Peptide) == 10,]$Allele))

colnames(betaherpes_6a_order_10mer)[2] <- "betaherpes_6a"
colnames(bk_order_10mer)[2] <- "bk"
colnames(cmv_order_10mer)[2] <- "cmv"
colnames(covid_order_10mer)[2] <- "covid"
colnames(ebv_order_10mer)[2] <- "ebv"
colnames(herpes_1_17_order_10mer)[2] <- "herpes_1_17"
colnames(herpes_2_hg52_order_10mer)[2] <- "herpes_2_hg52"
colnames(human_order_10mer)[2] <- "human"
colnames(random_order_10mer)[2] <- "random"

merged_order_10mers <- merge(betaherpes_6a_order_10mer, bk_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, cmv_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, covid_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, ebv_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, herpes_1_17_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, herpes_2_hg52_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, human_order_10mer, by="Var1")
merged_order_10mers <- merge(merged_order_10mers, random_order_10mer, by="Var1")

cormat <- cor(merged_order_10mers[,-1], method="spearman")

library(reshape2)
library(ggplot2)
#ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
#  geom_tile()

get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}
upper_tri <- get_upper_tri(cormat)
upper_tri

# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "yellow", 
                       midpoint = 0.4, limit = c(-0.2,1), space = "Lab", 
                       name="Spearman\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 5, hjust = 1))+
  coord_fixed()

```



```{r 11mer orders}
betaherpes_6a_order_11mer <- as.data.frame(table(betaherpes_6a_new_filt_0.5[nchar(betaherpes_6a_new_filt_0.5$Peptide) == 11,]$Allele))
bk_order_11mer <- as.data.frame(table(bk_new_filt_0.5[nchar(bk_new_filt_0.5$Peptide) == 11,]$Allele))
cmv_order_11mer <- as.data.frame(table(cmv_hlathena_0.5[nchar(cmv_hlathena_0.5$Peptide) == 11,]$Allele))
covid_order_11mer <- as.data.frame(table(covid_new_filt_0.5[nchar(covid_new_filt_0.5$Peptide) == 11,]$Allele))
ebv_order_11mer <- as.data.frame(table(ebv_new_filt_0.5[nchar(ebv_new_filt_0.5$Peptide) == 11,]$Allele))
herpes_1_17_order_11mer <- as.data.frame(table(herpes_1_17_new_filt_0.5[nchar(herpes_1_17_new_filt_0.5$Peptide) == 11,]$Allele))
herpes_2_hg52_order_11mer <- as.data.frame(table(herpes_2_hg52_new_filt_0.5[nchar(herpes_2_hg52_new_filt_0.5$Peptide) == 11,]$Allele))
human_order_11mer <- as.data.frame(table(human_new_filt_0.5[nchar(human_new_filt_0.5$pep) == 11,]$Allele))
random_order_11mer <- as.data.frame(table(random_new_filt_0.5[nchar(random_new_filt_0.5$Peptide) == 11,]$Allele))

colnames(betaherpes_6a_order_11mer)[2] <- "betaherpes_6a"
colnames(bk_order_11mer)[2] <- "bk"
colnames(cmv_order_11mer)[2] <- "cmv"
colnames(covid_order_11mer)[2] <- "covid"
colnames(ebv_order_11mer)[2] <- "ebv"
colnames(herpes_1_17_order_11mer)[2] <- "herpes_1_17"
colnames(herpes_2_hg52_order_11mer)[2] <- "herpes_2_hg52"
colnames(human_order_11mer)[2] <- "human"
colnames(random_order_11mer)[2] <- "random"

merged_order_11mers <- merge(betaherpes_6a_order_11mer, bk_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, cmv_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, covid_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, ebv_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, herpes_1_17_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, herpes_2_hg52_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, human_order_11mer, by="Var1")
merged_order_11mers <- merge(merged_order_11mers, random_order_11mer, by="Var1")

cormat <- cor(merged_order_11mers[,-1], method="spearman")

library(reshape2)
library(ggplot2)
#ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
#  geom_tile()

get_lower_tri<-function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}
# Get upper triangle of the correlation matrix
get_upper_tri <- function(cormat){
  cormat[lower.tri(cormat)]<- NA
  return(cormat)
}
upper_tri <- get_upper_tri(cormat)
upper_tri

# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "yellow", 
                       midpoint = 0.4, limit = c(-0.2,1), space = "Lab", 
                       name="Spearman\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 5, hjust = 1))+
  coord_fixed()

```

```{r save kmers}
kmers8 <- tibble(Pep=character(), Source=character(), Score=numeric())
kmers8 <- kmers8 %>% add_row(Pep=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 8,]$Peptide, Source="betaherpes_6a", Score=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=bk_new_filt[nchar(bk_new_filt$Peptide) == 8,]$Peptide, Source="bk", Score=bk_new_filt[nchar(bk_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 8,]$Peptide, Source="cmv", Score=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=covid_new_filt[nchar(covid_new_filt$Peptide) == 8,]$Peptide, Source="covid", Score=covid_new_filt[nchar(covid_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 8,]$Peptide, Source="ebv", Score=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 8,]$Peptide, Source="herpes_1_17", Score=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 8,]$Peptide, Source="herpes_2_hg52", Score=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=human_new_filt[nchar(human_new_filt$Peptide) == 8,]$Peptide, Source="human", Score=human_new_filt[nchar(human_new_filt$Peptide) == 8,]$Score)
kmers8 <- kmers8 %>% add_row(Pep=random_new_filt[nchar(random_new_filt$Peptide) == 8,]$Peptide, Source="random", Score=random_new_filt[nchar(random_new_filt$Peptide) == 8,]$Score)


kmers9 <- tibble(Pep=character(), Source=character(), Score=numeric())
kmers9 <- kmers9 %>% add_row(Pep=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 9,]$Peptide, Source="betaherpes_6a", Score=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=bk_new_filt[nchar(bk_new_filt$Peptide) == 9,]$Peptide, Source="bk", Score=bk_new_filt[nchar(bk_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 9,]$Peptide, Source="cmv", Score=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=covid_new_filt[nchar(covid_new_filt$Peptide) == 9,]$Peptide, Source="covid", Score=covid_new_filt[nchar(covid_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 9,]$Peptide, Source="ebv", Score=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 9,]$Peptide, Source="herpes_1_17", Score=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 9,]$Peptide, Source="herpes_2_hg52", Score=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=human_new_filt[nchar(human_new_filt$Peptide) == 9,]$Peptide, Source="human", Score=human_new_filt[nchar(human_new_filt$Peptide) == 9,]$Score)
kmers9 <- kmers9 %>% add_row(Pep=random_new_filt[nchar(random_new_filt$Peptide) == 9,]$Peptide, Source="random", Score=random_new_filt[nchar(random_new_filt$Peptide) == 9,]$Score)


kmers10 <- tibble(Pep=character(), Source=character(), Score=numeric())
kmers10 <- kmers10 %>% add_row(Pep=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 10,]$Peptide, Source="betaherpes_6a", Score=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=bk_new_filt[nchar(bk_new_filt$Peptide) == 10,]$Peptide, Source="bk", Score=bk_new_filt[nchar(bk_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 10,]$Peptide, Source="cmv", Score=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=covid_new_filt[nchar(covid_new_filt$Peptide) == 10,]$Peptide, Source="covid", Score=covid_new_filt[nchar(covid_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 10,]$Peptide, Source="ebv", Score=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 10,]$Peptide, Source="herpes_1_17", Score=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 10,]$Peptide, Source="herpes_2_hg52", Score=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=human_new_filt[nchar(human_new_filt$Peptide) == 10,]$Peptide, Source="human", Score=human_new_filt[nchar(human_new_filt$Peptide) == 10,]$Score)
kmers10 <- kmers10 %>% add_row(Pep=random_new_filt[nchar(random_new_filt$Peptide) == 10,]$Peptide, Source="random", Score=random_new_filt[nchar(random_new_filt$Peptide) == 10,]$Score)


kmers11 <- tibble(Pep=character(), Source=character(), Score=numeric())
kmers11 <- kmers11 %>% add_row(Pep=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 11,]$Peptide, Source="betaherpes_6a", Score=betaherpes_6a_new_filt[nchar(betaherpes_6a_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=bk_new_filt[nchar(bk_new_filt$Peptide) == 11,]$Peptide, Source="bk", Score=bk_new_filt[nchar(bk_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 11,]$Peptide, Source="cmv", Score=cmv_hlathena[nchar(cmv_hlathena$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=covid_new_filt[nchar(covid_new_filt$Peptide) == 11,]$Peptide, Source="covid", Score=covid_new_filt[nchar(covid_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 11,]$Peptide, Source="ebv", Score=ebv_new_filt[nchar(ebv_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 11,]$Peptide, Source="herpes_1_17", Score=herpes_1_17_new_filt[nchar(herpes_1_17_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 11,]$Peptide, Source="herpes_2_hg52", Score=herpes_2_hg52_new_filt[nchar(herpes_2_hg52_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=human_new_filt[nchar(human_new_filt$Peptide) == 11,]$Peptide, Source="human", Score=human_new_filt[nchar(human_new_filt$Peptide) == 11,]$Score)
kmers11 <- kmers11 %>% add_row(Pep=random_new_filt[nchar(random_new_filt$Peptide) == 11,]$Peptide, Source="random", Score=random_new_filt[nchar(random_new_filt$Peptide) == 11,]$Score)


write.csv(kmers8, "8mers_all_sources.csv")
write.csv(kmers9, "9mers_all_sources.csv")
write.csv(kmers10, "10mers_all_sources.csv")
write.csv(kmers11, "11mers_all_sources.csv")


```



```{r hlathenaranks}
hlathena_ranks <- merged_orders
hlathena_ranks[2] <- frank(-merged_orders[2])
hlathena_ranks[3] <- frank(-merged_orders[3])
hlathena_ranks[4] <- frank(-merged_orders[4])
hlathena_ranks[5] <- frank(-merged_orders[5])
hlathena_ranks[6] <- frank(-merged_orders[6])
hlathena_ranks[7] <- frank(-merged_orders[7])
hlathena_ranks[8] <- frank(-merged_orders[8])
hlathena_ranks[9] <- frank(-merged_orders[9])
hlathena_ranks[10] <- frank(-merged_orders[10])
hlathena_ranks[11] <- frank(-merged_orders[11])

hlathena_ranks$avg <- rowMeans(hlathena_ranks[,-1], na.rm=TRUE)
hlathena_ranks <- hlathena_ranks[order(hlathena_ranks$avg),]
library(matrixStats)
hlathena_ranks$sd <- rowSds(as.matrix(hlathena_ranks[,-1]))
write.csv(hlathena_ranks, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/hlathena_ranks.csv")

```


```{r netmhcpan correlations}
merged <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/merged_fraction_pep_binding.csv", row.names=1)
merged <- merged[,-1]

###Filtering merged based on 2000+ peptides alleles in training data for netmhcpan
big_allele_list <- c("HLA-A02:02","HLA-A02:06","HLA-A68:01","HLA-A02:03","HLA-A02:01","H-2-Kb","HLA-A11:01","HLA-A30:02","HLA-A31:01","HLA-B15:01","HLA-B35:01","HLA-A30:01","HLA-B07:02","HLA-A03:01","HLA-A29:02","HLA-A68:02","HLA-B08:01","HLA-B58:01","HLA-A23:01","HLA-A24:02","H-2-Db","HLA-A33:01","HLA-B40:01","HLA-B27:05","HLA-B44:02","HLA-B57:01","HLA-A01:01","HLA-B51:01","HLA-A26:01","HLA-A69:01","HLA-B18:01")
merged <- merged[big_allele_list,]
merged <- merged[,-11]

netmhcpan_ranks <- merged
netmhcpan_ranks[1] <- frank(-merged[1])
netmhcpan_ranks[2] <- frank(-merged[2])
netmhcpan_ranks[3] <- frank(-merged[3])
netmhcpan_ranks[4] <- frank(-merged[4])
netmhcpan_ranks[5] <- frank(-merged[5])
netmhcpan_ranks[6] <- frank(-merged[6])
netmhcpan_ranks[7] <- frank(-merged[7])
netmhcpan_ranks[8] <- frank(-merged[8])
netmhcpan_ranks[9] <- frank(-merged[9])
netmhcpan_ranks[10] <- frank(-merged[10])
netmhcpan_ranks$avg <- rowMeans(netmhcpan_ranks, na.rm=TRUE)
netmhcpan_ranks <- netmhcpan_ranks[order(netmhcpan_ranks$avg),]
library(matrixStats)
netmhcpan_ranks$sd <- rowSds(as.matrix(netmhcpan_ranks))
write.csv(netmhcpan_ranks, "/Users/nguyenau/Documents/Coding/PeptideAlleleBinding/netmhcpan_ranks")
mean(netmhcpan_ranks$sd[1:10])


###NETMHCPAN ALL VIRUS COR
cormat <- cor(merged, method="spearman", use="pairwise.complete.obs")
upper_tri <- get_upper_tri(cormat)
upper_tri

# Melt the correlation matrix
melted_cormat <- melt(upper_tri, na.rm = TRUE)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "yellow", 
                       midpoint = 0.5, limit = c(0,1), space = "Lab", 
                       name="Spearman\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 5, hjust = 1))+
  coord_fixed()
```


```{r physical property space}
#masterfile <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/umap/pipeline_umap/master_peptide_umap.csv")

#masterfile <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/umap/pipeline_umap/masterfile_features.csv")
#masterfile <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/umap/masterfile_with_rev_human_features.csv") ###WHEN WE HAVE MEMORY


#master.labels <- masterfile$source
#master.data <- masterfile[,6:37]
#library(umap)
#master.umap <- umap(master.data, low_memory=TRUE)


#new masterfile features after spiracle
#df <- data.frame(x=master.umap$layout[,1], y=master.umap$layout[,2], source=master.labels)

#masterfile_filt <- subset(masterfile, select=-c(allele,bindstatus))
#masterfile_filt <- distinct(masterfile_filt)
#rm(masterfile)
df <- read.csv("/Users/nguyenau/Documents/Coding/Viral_binding_affinity_analysis/austinpc_umap.csv")
df <- df[,-1]
df <- data.frame(x=df$V1, y=df$V2, source=df$source)
ggplot(data=df, aes(x=x, y=y)) + geom_point(aes(color=source))

library(GGally)
names <- unique(df$source)
plot_list = list()
count <- 1
for (i in 1:length(names))
{
  for (j in 1:length(names))
  {
    if (i != j)
    {
    tempdata <- df[df$source == names[i] | df$source == names[j],]
    p = ggplot(data=tempdata, aes(x=x, y=y)) + geom_point(aes(color=source))
    plot_list[[count]] = p
    count <- count + 1
    }
  }
}

for (i in 1:length(plot_list)) {
    file_name = paste("source_peptides_pairs_", i, ".tiff", sep="")
    tiff(file_name)
    print(plot_list[[i]])
    dev.off()
}
library(gridExtra)
pdf("PDFgrid_peptide_pairs.pdf")

```


```{r matrix bins}
require(ash)
matrix_bins <- tibble(x=character(), y=character(), diff=numeric())
names <- unique(df$source)

for (i in 1:length(names))
{
  for (j in 1:length(names))
  {
    x <- as.matrix(df[df$source == names[i],1:2])  
    #x <- matrix( rnorm(200), 100 , 2)
    ab <- matrix( c(-15,-15,15,15), 2, 2)      
    nbin <- c( 40, 40)                      # 1600 bins #compare binning to umap -> more bins(?)
    bins <- bin2(x, ab, nbin)
    bin_sol <- bins$nc
    sum(bin_sol)
    dim(x)[1]
    bin_sol1 <- bin_sol/(dim(x)[1])
    
    y <- as.matrix(df[df$source == names[j],1:2])  
    #x <- matrix( rnorm(200), 100 , 2)
    bins <- bin2(y, ab, nbin)
    bin_sol <- bins$nc
    sum(bin_sol)
    dim(y)[1]
    bin_sol2 <- bin_sol/(dim(y)[1])
    diff_bins <- bin_sol1 - bin_sol2
    sum_bins <- sum(abs(diff_bins))
    matrix_bins <- matrix_bins %>% add_row(x=names[i], y=names[j], diff=sum_bins)
  }
}

```

```{r}
library(reshape2)
matrix_bins <- as.data.frame(matrix_bins)
colnames(matrix_bins) <- c("Var1", "Var2", "Diff")
matrix_bins$Diff <- abs(matrix_bins$Diff)
matrix_bins$Var1 <- gsub("_scores", "", matrix_bins$Var1)
matrix_bins$Var2 <- gsub("_scores", "", matrix_bins$Var2)

melted_cormat <- melt(cormat)
diffs <- merge(matrix_bins, melted_cormat, by=c("Var1", "Var2"))
colnames(diffs)[3] <- "Matrix_diff"
colnames(diffs)[4] <- "Correlation"
diffs <- diffs[!diffs$Correlation == 1,]
cor.test(diffs$Matrix_diff, diffs$Correlation, method="spearman")
ggplot(diffs, aes(x=Matrix_diff, y=Correlation)) + geom_point() + geom_smooth(method="lm") + ggtitle("Matrix diff of binders (HLATHENA) vs Cor coefficient")

```

```{r filtered HLAthena 0.5}
df_filt <- read.csv("filtered_peps_umap_AustinPC.csv")
df_filt <- df_filt[,-1]
df_filt <- data.frame(x=df_filt$V1, y=df_filt$V2, source=df_filt$source)
ggplot(data=df_filt, aes(x=x, y=y)) + geom_point(aes(color=source))



require(ash)
matrix_bins_filt <- tibble(x=character(), y=character(), diff=numeric())
names <- unique(df_filt$source)

for (i in 1:length(names))
{
  for (j in 1:length(names))
  {
    x <- as.matrix(df_filt[df_filt$source == names[i],1:2])  
    #x <- matrix( rnorm(200), 100 , 2)
    ab <- matrix( c(-15,-15,15,15), 2, 2)      
    nbin <- c( 40, 40)                      # 1600 bins #compare binning to umap -> more bins(?)
    bins <- bin2(x, ab, nbin)
    bin_sol <- bins$nc
    sum(bin_sol)
    dim(x)[1]
    bin_sol1 <- bin_sol/(dim(x)[1])
    
    y <- as.matrix(df_filt[df_filt$source == names[j],1:2])  
    #x <- matrix( rnorm(200), 100 , 2)
    bins <- bin2(y, ab, nbin)
    bin_sol <- bins$nc
    sum(bin_sol)
    dim(y)[1]
    bin_sol2 <- bin_sol/(dim(y)[1])
    diff_bins <- bin_sol1 - bin_sol2
    sum_bins <- sum(abs(diff_bins))
    matrix_bins_filt <- matrix_bins_filt %>% add_row(x=names[i], y=names[j], diff=sum_bins)
  }
}

write.csv(matrix_bins_filt, "matrix_bins_filt_0.5_hlathena.csv")

library(reshape2)
matrix_bins_filt <- as.data.frame(matrix_bins_filt)
colnames(matrix_bins_filt) <- c("Var1", "Var2", "Diff")
matrix_bins_filt$Diff <- abs(matrix_bins_filt$Diff)
matrix_bins_filt$Var1 <- gsub("_scores", "", matrix_bins_filt$Var1)
matrix_bins_filt$Var2 <- gsub("_scores", "", matrix_bins_filt$Var2)

cormat <- cor(merged_order_8mers[,-1], method="spearman")
cormat <- cor(merged_orders[,-1], method="spearman")

melted_cormat <- melt(cormat)
diffs <- merge(matrix_bins_filt, melted_cormat, by=c("Var1", "Var2"))
colnames(diffs)[3] <- "Matrix_diff"
colnames(diffs)[4] <- "Correlation"
diffs <- diffs[!diffs$Correlation == 1,]
cor.test(diffs$Matrix_diff, diffs$Correlation, method="spearman")
ggplot(diffs, aes(x=Matrix_diff, y=Correlation)) + geom_point() + geom_smooth(method="lm")

```